languageCode = "en-us"
title = "Derwent Valley Railway"
baseURL = "https://dvr.org.au/"

[params]
	googleMapsApiKey = "AIzaSyD3mCeMb6721fhqX3A-HyEZ4vtBXiPRmBE"

[menu]
	[[menu.main]]
		identifier = "about-us"
		name = "About Us"
		url = "/about-us/"
		weight = 100
