languageCode = "en-us"
title = "Derwent Valley Railway"
baseURL = "https://dvr.org.au/"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
	googleMapsApiKey = "AIzaSyD3mCeMb6721fhqX3A-HyEZ4vtBXiPRmBE"
	cloudinaryBase = "https://res.cloudinary.com/dvrailway/image/upload"
	description = "The Derwent Valley Railway was established in 1990 to preserve the Derwent Valley railway line. We are a not for profit, volunteer based organisation. Currently, we are working closely with the state government to resume services from New Norfolk to Mt Field National Park."
	image = "/v1558609700/www/who_mzceyi.jpg"

[menu]
	[[menu.main]]
		identifier = "about-us"
		name = "About Us"
		url = "/about-us/"
		weight = 100
	
	[[menu.footer]]
		identifier = "github"
		name = "Contribute on GitHub"
		url = "https://github.com/derwentvalleyrailway/www"
		weight = 100
